[package]
name = "qdrant-client-service"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
prost = "0.14.1"
qdrant-client = "1.15.0"
tokio = "1.48.0"
tonic = "0.14.2"
tonic-prost = "0.14.2"
uuid = { version = "1.18.1", features = ["v4"] }

[build-dependencies]
tonic-prost-build = "0.14.2"
