syntax="proto3";

package lectureservice;

service LectureService {
  rpc Transcribe(TranscribeReq) returns (TranscribeRes);
  rpc Search(SearchReq) returns (SearchRes);
}

message AudioFile {
  bytes audio_data = 1;

  string file_name = 2;
}

message TranscribeReq {
  AudioFile file_payload = 1;

  string lecture_name = 2;

  string module = 3;
}

message TranscribeRes {
  optional string error_message = 1;
}

message Prompt {
  string prompt = 1;
}

message SearchReq {
  Prompt prompt_payload = 1;
  string module = 2;
}

// The response for a search request is just the created response from a large language model (or an error)
message SearchRes {
  oneof result {
    string response = 1;
    string error_message = 2;
  }
}