spring.application.name=bff

# gRPC Lecture Service Configuration
grpc.lecture-service.host=${LECTURE_SERVICE_HOST:localhost}
grpc.lecture-service.port=${LECTURE_SERVICE_PORT:40998}

# Server Configuration
server.port=${SERVER_PORT:40999}

# Logging Configuration
logging.level.de.bff=INFO
logging.level.io.grpc=INFO

# File Upload Configuration
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
